### ISSUE TITLE
tests with newtonsteps=0

### ISSUE THREAD

**Issue by mebrooks** [fishfollower/SAM#12]
It seems that with the argument `newtonsteps=0` travis and I get different results for `diag.cov`, `gradient`, and `sdrep$value`. The tests pass on my Mac (where I created the expected results), so maybe it's a platform issue? Also, travis tests were passing with `newtonsteps=3`.

**Comment by fishfollower** [comment]
How different? We could use 3 as default, but I fear we just get the issue
later on. The newton steps were introduced to fix an issue in one case. In
the general case they do nothing,  but takes a long time.

We can figure it out tomorrow.

Thanks a lot.

BTW do you know California well?

Cheers,

Anders

Den 7. feb. 2017 6.00 PM skrev "Mollie Brooks" <notifications@github.com>:

It seems that with the argument newtonsteps=0 travis and I get different
results for diag.cov, gradient, and sdrep$value. The tests pass on my Mac
(where I created the expected results), so maybe it's a platform issue?
Also, travis tests were passing with newtonsteps=3.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fishfollower/SAM/issues/12>, or mute the thread

**Comment by fishfollower** [comment]
Better to get same results on all platforms. kept newtonsteps=3 as default
